title: hfcmovies
description: Premium Movie Database
url: "https://narpatprihar2004-boop.github.io"
baseurl: ""  # <-- ISE KHALI RAKHO (Do not put /hfcmovies)
theme: minima
permalink: /:title/
paginate: 20
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
