title: hfcmovies
description: Premium Movie Database
url: "https://narpatprihar2004-boop.github.io"
baseurl: "/hfcmovies" # Agar repo ka naam hfcmovies hai to ye slash ke sath likho
theme: minima
permalink: /:title/
paginate: 20
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
