title: hfcmovies
description: Honest Movie Reviews
theme: minima
url: "https://narpatprihar2004-boop.github.io"
baseurl: "/hfcmovies"   # <-- YAHAN GOR KAREIN (Slash ke sath repo ka naam)
permalink: /:title/
markdown: kramdown
